CREATE OR REPLACE TABLE iracing_stg.stg_cars
 (
    car_id Int64,
    car_name Nullable(String),
    car_name_abbreviated Nullable(String),
    ai_enabled Nullable(Bool),
    allow_number_colors Nullable(Bool),
    allow_number_font Nullable(Bool),
    allow_sponsor1 Nullable(Bool),
    allow_sponsor2 Nullable(Bool),
    allow_wheel_color Nullable(Bool),
    award_exempt Nullable(Bool),
    car_dirpath Nullable(String),
    car_types Array(Tuple(
        car_type Nullable(String)
        )),
    car_weight Nullable(Int64),
    categories Array(Nullable(String)),
    created Nullable(String),
    first_sale Nullable(String),
    forum_url Nullable(String),
    free_with_subscription Nullable(Bool),
    has_headlights Nullable(Bool),
    has_multiple_dry_tire_types Nullable(Bool),
    has_rain_capable_tire_types Nullable(Bool),
    hp Nullable(Int64),
    is_ps_purchasable Nullable(Bool),
    max_power_adjust_pct Nullable(Int64),
    max_weight_penalty_kg Nullable(Int64),
    min_power_adjust_pct Nullable(Int64),
    package_id Nullable(Int64),
    patterns Nullable(Int64),
    price Nullable(Float64),
    price_display Nullable(String),
    rain_enabled Nullable(Bool),
    retired Nullable(Bool),
    search_filters Nullable(String),
    sku Nullable(Int64),
    car_rules Array(Tuple(
        rule_category Nullable(String),
        text Nullable(String)
        )),
    detail_copy Nullable(String),
    detail_screen_shot_images Nullable(String),
    detail_techspecs_copy Nullable(String),
    folder Nullable(String),
    gallery_images Nullable(String),
    gallery_prefix Nullable(String),
    group_image Nullable(String),
    group_name Nullable(String),
    large_image Nullable(String),
    logo Nullable(String),
    small_image Nullable(String),
    sponsor_logo Nullable(String),
    template_path Nullable(String),
    car_make Nullable(String),
    car_model Nullable(String),
    site_url Nullable(String)
)
    ENGINE = Memory